version: "3.7"

services:
  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_PASSWORD=thisismypostgres"
    ports:
      - 5432:5432
    volumes:
    - "dbdata:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  dbdata: