version: "3.7"

services:
  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_PASSWORD=thisismypostgres"
    volumes:
    - "dbdata:/var/lib/postgresql/data"

  api:
    image: imabad.dev/do/api:latest
    ports:
      - 8080:8080
    volumes:
    - "./config.prod.json:/dist/config.json"
volumes:
  dbdata: